version: '3.6'

services:
  mongodb:
    image: mongo:6.0
    container_name: mongo-database
    ports:
      - 27017:27017
    environment:
      - MONGO_INITDB_DATABASE=test
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=admin
